#!/bin/bash
. /usr/lib64/nagios/plugins/utils.sh

RAWSTATUS=`/etc/init.d/erlrtpproxy status_verbose 2>/dev/null`
STATUS=$?

[ $STATUS = 0 ] && CALLS=`echo $RAWSTATUS | cut -d " " -f 4` || CALLS="0"

if [ $STATUS = 0 ]
then
	echo "rtpproxy is up and ready. Serves $CALLS calls now.|calls=$CALLS"
	exit 0
fi

echo "rtpproxy DOES NOT WORKING properly.|calls=$CALLS"
exit 1
