#!/usr/bin/python

import urllib
import json
import getopt
import os
import sys

# Nagios return codes
# https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins-scripts/utils.sh.in#L3

STATE_OK	= 0
STATE_WARNING	= 1
STATE_CRITICAL	= 2
STATE_UNKNOWN	= 3
STATE_DEPENDENT	= 4

if __name__ == '__main__':
	HOST = "localhost"
	PORT = "8442"
	JSON = {}

	try:
		opts, args = getopt.getopt(sys.argv[1:], 'u:p:')
	except getopt.GetoptError:
		print('usage: %s -u url') % sys.argv[0]
		sys.exit(STATE_CRITICAL)

	for o, a in opts:
		if o == "-u":
			HOST = a
		elif o == "-p":
			PORT = a

	ADDR = "http://%s:%s/json/?callnum" % (HOST, PORT)

	try:
		JSON = json.load(urllib.urlopen(ADDR))
	except Exception:
		sys.exit(STATE_CRITICAL)

	print ("Alive. Calls: %s") % JSON["callnum"]
	sys.exit(STATE_OK)
